/*
RECIPE TEMPLATE:
  key: {
    title: '',
    name: 'key',
    description: '',
    tags: [],
    ingredients: [],
    directions: [],
    notes: []
  },
*/

const recipes = {
  guacamole: {
    title: 'Guacamole',
    name: 'guacamole',
    description:
      'A guac recipe refined in San Francisco and perfected by many Youtube videos',
    tags: ['vegan', 'appetizer', 'dip'],
    ingredients: [
      '5-6 Hass Avocados',
      '1/2 Red Onion',
      '1 Jalapeno',
      '2 Serranos',
      '~3 cloves Garlic',
      '1/2 - 1 Lemon',
      '1-2 Tomatoes',
      'Salt',
    ],
    directions: [
      'Finely dice onion and peppers; mince garlic; transfer to a sturdy mixing bowl',
      "Add some salt to mixture; mash with pestle until onions an peppers don't make as much crunching noise",
      'Halve and cube avocados; scoop into mixing bowl',
      'Mash with pestle and/or fork to desired chunkiness',
      'Mix in juice of half a lemon',
      'Deseed and dice tomato(es); stir into mixture',
      'Add lemon, salt and other desired seasonings to taste',
      'Serve with chips or on a burrito or something',
    ],
    notes: [],
  },
  artichoke_dip: {
    title: 'Artichoke Heart Dip',
    name: 'artichoke_dip',
    description:
      'Not that cheesy-spinach-dip-with-a-hint-of-artichoke sorry excuse for artichoke dip you get at restaurants.',
    tags: ['appetizer', 'dip'],
    ingredients: [
      '24-42oz marinated artichoke hearts',
      '1-2 green onions',
      '2-4 garlic cloves',
      '1 Roasted Red Pepper (optional)',
      'Parmigiano Reggiano',
      'Mayonnaise (or Vegannaise)',
      '1-2 tbsp Pine Nuts (optional)',
      'Salt',
      'Pepper',
      'Cayenne',
      '1-2 baguettes',
    ],
    directions: [
      'Dice artichoke hearts & roasted red pepper; mince garlic & green onion; place in baking dish',
      'Grate (ideally with a microplane) a good mound of Parm into backing dish (1-2 cups in volume)',
      'Mix it all together',
      'One (table)spoon at a time: add mayo, stir until combined, assess; shooting for just enough mayo to hold it together',
      'Season to taste with salt, pepper, and cayenne',
      "Sprinkle pine nuts over top (don't cover it, just enough to get a couple per spoonful)",
      'Place in 375&deg; oven for ~20 min or until slightly bubbling around the edges',
      'Place baguettes in oven for about 5 min towards the end; remove from oven and slice into 1-or-2-bite size pieces',
      'Serve with spoons in dip for scooping onto baguette slices',
    ],
    notes: [
      'Vegannaise adds a nice tanginess to the dip, but reduces its structural integrity',
      "The quality of the marinated artichokes is a big deal; don't cut costs with the artichokes",
    ],
  },
  brushcetta: {
    title: 'Tomato Bruschetta',
    name: 'bruschetta',
    description: '',
    tags: [],
    ingredients: [],
    directions: [],
    notes: [],
  },
  thai_peanut_noodles: {
    title: 'Thai Peanut Noodles',
    name: 'thai_peanut_noodles',
    description: '',
    tags: [],
    ingredients: [],
    directions: [],
    notes: [],
  },
  pesto: {
    title: 'Pesto',
    name: 'pesto',
    description: '',
    tags: [],
    ingredients: [],
    directions: [],
    notes: [],
  },
  alfredo: {
    title: 'Alfredo',
    name: 'alfredo',
    description: '',
    tags: [],
    ingredients: [],
    directions: [],
    notes: [],
  },
  orzo_salad: {
    title: 'Orzo Salad',
    name: 'orzo_salad',
    description: '',
    tags: [],
    ingredients: [],
    directions: [],
    notes: [],
  },
  sourdough_bread: {
    title: 'Sourdough Bread',
    name: 'sourdough_bread',
    courtesy_of: 'Luke Peterson',
    description: '',
    tags: [],
    ingredients: [],
    directions: [],
    notes: [],
  },
  beet_burgers: {
    title: 'Beet Burgers',
    name: 'beet_burgers',
    courtesy_of: 'The Vegetarian Cookbook',
    description: '',
    tags: [],
    ingredients: [],
    directions: [],
    notes: [],
  },
  ultimate_burgers: {
    title: 'Ultimate Burgers',
    name: 'ultimate_burgers',
    courtesy_of: 'The Vegetarian Cookbook',
    description: '',
    tags: [],
    ingredients: [],
    directions: [],
    notes: [],
  },
  roasted_veggies: {
    title: 'Roasted Veggies',
    name: 'roasted_veggies',
    description: '',
    tags: [],
    ingredients: [],
    directions: [],
    notes: [],
  },
  cream_cheese_wontons: {
    title: 'Cream Cheese Wontons',
    name: 'cream_cheese_wontons',
    description: '',
    tags: [],
    ingredients: [],
    directions: [],
    notes: [],
  },
  mushroom_stroganoff: {
    title: 'Mushroom Stroganoff',
    name: 'mushroom_stroganoff',
    description: '',
    tags: [],
    ingredients: [],
    directions: [],
    notes: [],
  },
  marinara: {
    title: 'Marinara',
    name: 'marinara',
    courtesy_of: 'Dad',
    description: '',
    tags: [],
    ingredients: [],
    directions: [],
    notes: [],
  },
  tortilla_wraps: {
    title: 'Tortilla Wraps',
    name: 'tortilla_wraps',
    courtesy_of: 'Matt & Alyssa Kirby',
    description: '',
    tags: [],
    ingredients: [],
    directions: [],
    notes: [],
  },
  hummus: {
    title: 'Hummus',
    name: 'hummus',
    description: '',
    tags: [],
    ingredients: [],
    directions: [],
    notes: [],
  },
  mac_n_cheese_pizza: {
    title: "Mac 'n' Cheese Pizza",
    name: 'mac_n_cheese_pizza',
    courtesy_of: 'Dad',
    description: '',
    tags: [],
    ingredients: [],
    directions: [],
    notes: [],
  },
  ramen_noodles: {
    title: 'Ramen Noodles',
    name: 'ramen_noodles',
    description: '',
    tags: [],
    ingredients: [],
    directions: [],
    notes: [],
  },
  dad_pizza_dough: {
    title: "Dad's Pizza Dough",
    name: 'dad_pizza_dough',
    courtesy_of: 'Dad',
    description: '',
    tags: [],
    ingredients: [],
    directions: [],
    notes: [],
  },
  acorn_squash_pasta: {
    title: 'Acorn Squash Pasta',
    name: 'acorn_squash_pasta',
    courtesy_of: 'Unnamed Workiva Cafe Chef',
    description: '',
    tags: [],
    ingredients: [],
    directions: [],
    notes: [],
  },
  roasted_veggie_hoagies: {
    title: 'Roasted Veggie & Mushroom Hoagies',
    name: 'roasted_veggie_hoagies',
    description: '',
    tags: [],
    ingredients: [],
    directions: [],
    notes: [],
  },
  risotto: {
    title: 'Risotto',
    name: 'risotto',
    description: '',
    tags: [],
    ingredients: [],
    directions: [],
    notes: [],
  },
  salsa: {
    title: 'Salsa',
    name: 'salsa',
    courtesy_of: 'Tristan Duyvejonck',
    description: '',
    tags: [],
    ingredients: [],
    directions: [],
    notes: [],
  },
  butter_cream_sauce: {
    title: 'Butter Cream Sauce',
    name: 'butter_cream_sauce',
    description: '',
    tags: [],
    ingredients: [],
    directions: [],
    notes: [],
  },
  mayonnaise: {
    title: 'Mayonnaise',
    name: 'mayonnaise',
    description: '',
    tags: [],
    ingredients: [],
    directions: [],
    notes: [],
  },
  vodka_sauce: {
    title: 'Vodka Sauce',
    name: 'vodka_sauce',
    description: '',
    tags: [],
    ingredients: [],
    directions: [],
    notes: [],
  },
  luke_pizza_dough: {
    title: 'Lukes Pizza Dough',
    name: 'luke_pizza_dough',
    courtesy_of: 'Luke PEterson',
    description: '',
    tags: [],
    ingredients: [],
    directions: [],
    notes: [],
  },
  mushrooms: {
    title: 'Sauteed Mushrooms',
    name: 'mushrooms',
    description: '',
    tags: [],
    ingredients: [],
    directions: [],
    notes: [],
  },
  stomping_grounds_paninis: {
    title: 'Stomping Grounds Paninis',
    name: 'stomping_grounds_paninis',
    description: '',
    tags: [],
    ingredients: [],
    directions: [],
    notes: [],
  },
  roasted_pepper_pasta: {
    title: 'Roasted Red Pepper Pasta',
    name: 'roasted_pepper_pasta',
    description: '',
    tags: [],
    ingredients: [],
    directions: [],
    notes: [],
  },
  mushroom_bruschetta: {
    title: 'Mushroom Bruschetta',
    name: 'mushroom_bruschetta',
    description: '',
    tags: [],
    ingredients: [],
    directions: [],
    notes: [],
  },
  rosie_thai_curry: {
    title: "Rosie's Thai Curry",
    name: 'rosie_thai_curry',
    courtesy_of: 'Roisin Welch',
    description: '',
    tags: [],
    ingredients: [],
    directions: [],
    notes: [],
  },
};

if (typeof window === 'undefined') module.exports = recipes;
