#!/bin/bash

recipesDir="recipes";

rm -rf "$recipesDir";
mkdir "$recipesDir";

mapfile -t keyValues < <(node scripts/get_recipes.js)
for keyValue in "${keyValues[@]}"; do
  ./scripts/new-recipe $keyValue
done

buildDir="build"

rm -rf "$buildDir"
mkdir "$buildDir"

toCopy=(
  "index.html"
  "index.css"
  "recipes.js"
  "Recipe.js"
  "recipes"
  "favicon.ico"
)

cp -r ${toCopy[@]} "${buildDir}/"
